Update helper scripts for space creator

diff --git a/misc/helper-scripts/taste-edit-code b/misc/helper-scripts/taste-edit-code
--- a/misc/helper-scripts/taste-edit-code
+++ b/misc/helper-scripts/taste-edit-code
@@ -15,6 +15,8 @@ fi
 INFO="${COLORON}[INFO]${COLOROFF}"
 ERROR="${REDCOLORON}[ERROR]${COLOROFF}"
 
+taste-xml-to-aadl || exit 1
+
 
 if [[ $1 != "C" && $1 != "Ada" && $1 != "SDL" && $1 != "CPP" && "$1" != "Blackbox_Device" ]]
 then
@@ -25,10 +27,10 @@ fi
 # Check if the project works with kazoo. If so, use the makefile rule to edit the code
 if [[ -f Makefile && $(grep KAZOO Makefile) != "" ]]
 then
-    cd work/"$2"/"$1"
+    cd work/"${2,,}"/"$1"
     make edit
     exit 0
 else
-    echo 'You should switch to kazoo...'
+    echo -e "${ERROR} Code skeleton generation failed"
 fi
 
