Update scripts for space creator

diff --git a/misc/helper-scripts/taste-xml-to-aadl b/misc/helper-scripts/taste-xml-to-aadl
--- a/misc/helper-scripts/taste-xml-to-aadl
+++ b/misc/helper-scripts/taste-xml-to-aadl
@@ -22,26 +22,47 @@ then
     exit 1
 fi
 
+# Figure out the project file name
+# It should be the only .pro file that has a .pro.user file next to it
+projectFile=$(ls *.pro)
+projectConfig=$projectFile.user
+if [ $projectConfig != $projectFile.user ]
+then
+    echo -e "${ERROR} No Space Creator project file found"
+    exit 1
+fi
+
+
 # TODO: We should extract the list of ASN.1 and ACN files from the .pro file
 taste-update-data-view *.asn || exit 1
 
-aadlconverter -o interfaceview.xml -t $(taste-config --prefix)/share/xml2aadl/interfaceview.tmplt -x InterfaceView.aadl || exit 1 
-
-# Create/update a deployment view for Linux target (to be removed when we have a DV editor)
-aadlconverter -o interfaceview.xml -t $(taste-config --prefix)/share/xml2dv/interfaceview.tmplt -x DeploymentView.aadl || exit 1 
-
-# To build the system, kazoo needs a concurrency view property files
-if [ ! -f ConcurrencyView_Propertiess.aadl ]
+if [ interfaceview.xml -nt InterfaceView.aadl ]
 then
-    touch ConcurrencyView_Properties.aadl
+    # Interface view was updated since the last generation of the AADL file
+    aadlconverter -o interfaceview.xml -t $(taste-config --prefix)/share/xml2aadl/interfaceview.tmplt -x InterfaceView.aadl || exit 1
+    
+    # Create/update a deployment view for Linux target (to be removed when we have a DV editor)
+    aadlconverter -o interfaceview.xml -t $(taste-config --prefix)/share/xml2dv/interfaceview.tmplt -x DeploymentView.aadl || exit 1 
+
+    # To build the system, kazoo needs a concurrency view property files
+    if [ ! -f ConcurrencyView_Propertiess.aadl ]
+    then
+        touch ConcurrencyView_Properties.aadl
+    fi
+
+    #  Generate code skeletons
+    if [[ -f Makefile && $(grep KAZOO Makefile) != "" ]]
+    then
+        make skeletons || exit 1
+    else
+        echo -e "${INFO} Initializing Kazoo project file (TODO)"
+        taste init
+        make skeletons || exit 1
+    fi
 fi
 
-#  Generate code skeletons
-if [[ -f Makefile && $(grep KAZOO Makefile) != "" ]]
+echo projectFile = $projectFile
+if [[ $(grep taste.pro $projectFile) == "" ]]
 then
-    make skeletons || exit 1
-else
-    echo -e "${INFO} Initializing Kazoo project file (TODO)"
-    taste init
-    make skeletons || exit 1
+   echo 'include(work/taste.pro)' >> $projectFile
 fi
